// src/App.vue
<template>
  <div id="app">
    <div id="container-not-authenticated" v-if="!$store.state.user">
      <WelcomePage ref="welcome_page" />
    </div>
    <div id="container-authenticated" v-else>
      <Header ref="header" />
      <SearchMenu ref="search-menu" />
      <Viewer ref="viewer" />
      <FileBrowser ref="file_browser" />
      <ContinueWatching ref="continue_watching" />
      <CarouselHidder :left="'-2.5%'" />
      <Carousel v-for="i in this.carouselCount" :ref="'carousel-' + (i - 1)" :key="i - 1" :id="i - 1" :title="GetCarouselTitle(i)" />
      <CarouselHidder :left="'92.5%'" />
    </div>
  </div>
</template>

<script>
import WelcomePage from './components/Users/WelcomePage.vue'
import Carousel from './components/Carousel.vue'
import Viewer from './components/Viewer.vue'
import Constants from './constantsClient'
import Header from './components/Header/Header.vue'
import ContinueWatching from './components/ContinueWatching.vue'
import SearchMenu from './components/SearchMenu.vue'
import CarouselHidder from './components/CarouselHidder.vue'
import FileBrowser from './components/FileBrowser/FileBrowser.vue'

export default {
  name: 'App',
  created() {
    fetch('/api/count')
      .then((res) => {
        return res.json()
      })
      .then((res) => {
        this.itemCount = res.count
        this.carouselCount = Number.parseInt(res.count / (Constants.itemsPerSlide * Constants.slidesPerCarousel) + 1)
      })
  },
  components: {
    Carousel,
    Viewer,
    Header,
    ContinueWatching,
    SearchMenu,
    CarouselHidder,
    FileBrowser,
    WelcomePage,
  },
  data() {
    return {
      carouselCount: 0,
      itemCount: 0,
      itemBeingPreviewed: null,
    }
  },
  methods: {
    GetCarouselTitle(index) {
      const language = this.$store.state.user.languages.text

      if (language == 'fre-FR') {
        var titles = [
          'Les incontournables de Rachinflix',
          "Thriller à l'intrigue envoûtante",
          'Les plus gros succès sur Rachinflix',
          'Tendances actuelles',
          'Les programmes les plus chauds de ta région',
          'Programmes historiques avec des personnages et des combats violents',
          'Programmes originaux Rachinflix',
          'Notre sélection pour vous',
          'Programmes à regarder sans modérations',
          'Series primées aux Emmys Awards à regarder sans modération',
          'Nouveautés',
        ]
      } else if (language == 'eng-US') {
        titles = [
          "Rachinflix' must-haves",
          'Thriller with bewitching plot',
          'The biggest hits on Rachinflix',
          'Current Trends',
          'The hottest programs in your area',
          'Historical programs with characters and violent fights',
          'Original Rachinflix programs',
          'Our selection for you',
          'Programs to watch without moderation',
          'Emmy Award-winning series to watch without moderation',
          'News',
        ]
      }

      index %= titles.length
      return titles[index]
    },
  },
}
</script>

<style>
@font-face {
  font-family: operatormono;
  src: url(../fonts/OperatorMono-Medium.otf);
}
@font-face {
  font-family: operatormonolight;
  src: url(../fonts/OperatorMono-Light.otf);
}
@font-face {
  font-family: operatormonobold;
  src: url(../fonts/OperatorMono-Bold.otf);
}
@font-face {
  font-family: operatormonoitalic;
  src: url(../fonts/OperatorMono-MediumItalic.otf);
}
@font-face {
  font-family: operatormonolightitalic;
  src: url(../fonts/OperatorMono-LightItalic.otf);
}
@font-face {
  font-family: operatormonobolditalic;
  src: url(../fonts/OperatorMono-BoldItalic.otf);
}
::-webkit-scrollbar {
  background-color: black;
  width: 1vw;
}
::-webkit-scrollbar-thumb {
  background-color: rgb(40, 40, 40);
  width: 1vw;
}
video {
  outline: none;
}
img {
  outline: none;
}
a {
  color: inherit;
  text-decoration: none;
  outline: 0;
}
a:visited {
  color: inherit;
}
/* From netflix */
select {
  outline: 0;
  height: 2.5rem;
  margin-left: 2%;
  padding-left: 10px;
  line-height: 2.5rem;
  letter-spacing: 1px;
  font-size: 1.25rem;
  font-weight: bold;
  box-sizing: border-box;
  border: 1px solid rgba(255, 255, 255, 0.9);
  display: inline-block;
  color: #fff;
  background-color: #000;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  border-radius: 0;
  position: relative;
  padding-right: 10px;
}
body {
  overflow-x: hidden;
  margin: 0;
  color: #ddd;
  background-color: #141414;
  font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
  scroll-behavior: smooth;
}
#app {
  position: relative;
  width: 99vw;
}
.blur-background > div > div > div > *:not(.unblur) {
  filter: grayscale(100%);
}
#container-authenticated {
  margin-top: 5%;
}

@media screen and (min-width: 1250px) {
  body {
    font-size: 12pt;
  }
}
@media screen and (max-width: 1249px) {
  body {
    font-size: 8pt;
  }
}
</style>

// client/src/App.tsx
import { WelcomePage } from 'components/authentication-page/welcome'
import { ClientEvent, useEventHandler } from 'components/common/events'
import { Store, useStore } from 'components/common/store'
import { HeaderComponent } from 'components/header/header'
import { ManagementPage } from 'components/management/managementPage'
import { itemsPerSlide, itemsPerVerticalCarousel, slidesPerCarousel } from 'config'
import { useApi } from 'contexts/api'
import { FilmHateoas, SerieHateoas, UserHateoas } from 'interface'
import { observer, useLocalObservable } from 'mobx-react'
import React, { useEffect } from 'react'
import './App.scss'

export type Item = FilmHateoas | SerieHateoas
export type Slide = Array<Item | undefined>
export type HorizontalCarousel = Slide[]
export type VerticalCarousel = Item[]

function getCarouselTitle(index: number, store: Store): string {
  const language = store.getUserLanguage('text')
  let titles: Array<string> = []

  if (language === 'fre-FR') {
    titles = [
      'Les incontournables de Rachinflix',
      "Thriller à l'intrigue envoûtante",
      'Les plus gros succès sur Rachinflix',
      'Tendances actuelles',
      'Les programmes les plus chauds de ta région',
      'Programmes historiques avec des personnages et des combats violents',
      'Programmes originaux Rachinflix',
      'Notre sélection pour vous',
      'Programmes à regarder sans modérations',
      'Series primées aux Emmys Awards à regarder sans modération',
      'Nouveautés'
    ]
  } else if (language === 'eng-US') {
    titles = [
      "Rachinflix' must-haves",
      'Thriller with bewitching plot',
      'The biggest hits on Rachinflix',
      'Current Trends',
      'The hottest programs in your area',
      'Historical programs with characters and violent fights',
      'Original Rachinflix programs',
      'Our selection for you',
      'Programs to watch without moderation',
      'Emmy Award-winning series to watch without moderation',
      'News'
    ]
  }

  index %= titles.length
  return titles[index]
}

export const App = observer(() => {
  const store = useStore()
  const eventHandler = useEventHandler()
  const api = useApi()

  const state = useLocalObservable(() => ({
    carousels: {
      horizontal: undefined as HorizontalCarousel[] | undefined,
      vertical: undefined as VerticalCarousel[] | undefined,
      ratio: undefined as number | undefined
    },
    browsed: undefined as FilmHateoas | SerieHateoas | undefined,
    file: undefined as FilmHateoas | SerieHateoas | undefined,
    profile: undefined as Array<FilmHateoas | SerieHateoas> | undefined
  }))

  useEffect(() => {
    eventHandler.addListener(ClientEvent.OpenBrowser, (details: FilmHateoas | SerieHateoas) => {
      state.browsed = details
    })
    eventHandler.addListener(ClientEvent.CloseBrowser, () => {
      state.browsed = undefined
    })
    eventHandler.addListener(ClientEvent.OpenPlayer, (details: FilmHateoas | SerieHateoas) => {
      state.file = details
    })
    eventHandler.addListener(ClientEvent.ClosePlayer, () => {
      state.profile = undefined
      // Reload the profile
      setTimeout(() => {
        api
          .query<Array<FilmHateoas | SerieHateoas>>(store.getUser() as UserHateoas, 'getProfile')
          .then(profile => (state.profile = profile))
      }, 200)
      // Delete the player after it faded out
      setTimeout(() => {
        state.file = undefined
      }, 600)
    })
    eventHandler.addListener(
      ClientEvent.RequestCustomEpisode,
      (request: { details: SerieHateoas; season: number; episode: number }) => {
        const { details, season, episode } = request
        details._actions.requestCustomEpisode.body = {
          season,
          episode
        }
        api.query<SerieHateoas>(details, '@requestCustomEpisode').then(details => {
          state.browsed = undefined
          state.file = details
        })
      }
    )
  }, [])

  useEffect(() => {
    if (!store.user) {
      return
    }

    state.carousels.horizontal = undefined
    state.carousels.vertical = undefined
    state.carousels.ratio = undefined
    state.profile = undefined

    api.get<Array<FilmHateoas | SerieHateoas>>(`/carousels`).then(files => {
      const overflow = files.length % (itemsPerSlide * slidesPerCarousel)
      const verticalItems = files.slice(0, overflow)
      const horizontalItems = files.slice(overflow)

      state.carousels.vertical = new Array(Math.floor(verticalItems.length / itemsPerVerticalCarousel)).fill([])
      while (verticalItems.length > 0) {
        for (let i = 0; i < state.carousels.vertical.length; ++i) {
          const item = verticalItems.pop()
          if (!item) break
          state.carousels.vertical[i].push(item)
        }
      }

      const slides = []
      for (let i = 0; i < horizontalItems.length; i += itemsPerSlide) {
        slides.push(horizontalItems.slice(i, i + itemsPerSlide))
      }

      const carousels = []
      for (let i = 0; i < slides.length; i += slidesPerCarousel) {
        carousels.push(slides.slice(i, i + slidesPerCarousel))
      }

      state.carousels.horizontal = carousels
      state.carousels.ratio = Math.floor(state.carousels.horizontal.length / state.carousels.vertical.length)
      api
        .query<Array<FilmHateoas | SerieHateoas>>(store.getUser() as UserHateoas, 'getProfile')
        .then(profile => (state.profile = profile))
    })
  }, [store.user, store.user?.languages.text])

  return (
    <>
      {!store.user ? (
        <div id={'container-unauthenticated'}>
          <WelcomePage />
        </div>
      ) : (
        <div id={'container-authenticated'}>
          <HeaderComponent />
          <div id="rachinflix-body">
            <ManagementPage />
            {/* {state.browsed && <BrowserComponent details={state.browsed} />}
            {state.file && <PlayerComponent file={state.file} />}
            <VerticalCarouselComponent
              title={
                store.getUser()
                  ? store.getUserLanguage('text') === 'fre-FR'
                    ? `Reprendre le profil de ${store.getUsername()}`
                    : `Resume ${store.getUsername()}'s profile`
                  : ''
              }
              items={state.profile}
            />
            {!state.carousels.horizontal ? (
              <>
                <HorizontalCarouselComponent
                  title={getCarouselTitle(0, store)}
                  slides={new Array(slidesPerCarousel).fill(new Array(itemsPerSlide).fill(undefined))}
                />
                <HorizontalCarouselComponent
                  title={getCarouselTitle(1, store)}
                  slides={new Array(slidesPerCarousel).fill(new Array(itemsPerSlide).fill(undefined))}
                />
              </>
            ) : (
              state.carousels.horizontal.map((slides: Slide[], i: number) => {
                if (state.carousels.ratio == null || state.carousels.vertical == null) return

                const addVerticalSlide = i > 0 && i % state.carousels.ratio === 0
                return (
                  <>
                    <HorizontalCarouselComponent
                      key={`horizontal-carousel-${i}`}
                      title={getCarouselTitle(i, store)}
                      slides={slides}
                    />
                    {addVerticalSlide && (
                      <VerticalCarouselComponent
                        key={`vertical-carousel-${i}`}
                        title={getCarouselTitle(i + 4, store)}
                        items={state.carousels.vertical[i / state.carousels.ratio - 1]}
                      />
                    )}
                  </>
                )
              })
            )} */}
          </div>
        </div>
      )}
    </>
  )
})
